// Generated by CoffeeScript 1.6.2
(function() {
  var ObjectStore, events,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  events = require('events');

  ObjectStore = (function(_super) {
    __extends(ObjectStore, _super);

    ObjectStore.JSON_OBJECT_PREFIX = "br_json_obj:";

    function ObjectStore(location) {
      if (location == null) {
        location = null;
      }
    }

    ObjectStore.prototype.set = function(key, value, callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.get = function(key, callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.del = function(key, callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.has = function(key, callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.keys = function(pattern, callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.flush = function(callback) {
      throw new Error("Not implemented");
    };

    ObjectStore.prototype.getStringKey = function(key) {
      if (typeof key === 'object') {
        return JSON.stringify(key);
      } else {
        return key;
      }
    };

    return ObjectStore;

  })(events.EventEmitter);

  module.exports = ObjectStore;

}).call(this);
